### ISSUE TITLE
login issues due to recent launcher changes from NCSoft

### ISSUE THREAD

**Issue by Syzuna** [RedDot-3ND7355/BnS-Buddy#1]
Hey!

I appreciate your work and it is a rly good launcher you made there!
It helped me a lot but since the maint today I cant login anymore using BnSBuddy bcs they changed sth. on the authentication system!
Looks like they pass a token now as mandatory to login!

Any chance for a workaroung? Pls Q.Q

Regards

**Comment by RedDot-3ND7355** [comment]
BnS Buddy updated ;)
Now supports auth token generation for na and eu ^^
Update Buddy then follow these steps!
(make sure game is updated on ncsoft launcher first!)
Step 1: Launch BnS Buddy
Step 2: Click Restore
Step 3: Close BnS Buddy
Step 4: Open settings.ini
Step 5: ncsoftlogin = true
Step 6: Save + Close settings.ini
Step 7: Run BnS Buddy as admin
Step 8: Enter your log in details
Step 9: Press patch to launch the game
