### ISSUE TITLE
stuck in update loop

### ISSUE THREAD

**Issue by adorhun** [RedDot-3ND7355/BnS-Buddy#1]
hi!
the app is stuck in an update loop from 5.4 to 5.5.

**Comment by RedDot-3ND7355** [comment]
Hi, let it run 3-4 times in a loop and it will replace itself :)
The newest 5.5 fixes that problem. <3

**Comment by RedDot-3ND7355** [comment]
New external updater released! Fixes all related issue to integrated updater wich relied on cmd.
