### ISSUE TITLE
Development Question

### ISSUE THREAD

**Issue by DemonRem** [RedDot-3ND7355/BnS-Buddy#13]
this project still get updates or it's abandoned?

**Comment by RedDot-3ND7355** [comment]
It still get's updates, i was planning in pushing the next update after 5.8.9.4 is released.

**Comment by DemonRem** [comment]
Dear @RedDot-3ND7355 do you still updating this git?

**Comment by RedDot-3ND7355** [comment]
@DemonRem

I'm currently working on a new update with new features.
After that a new stable build has been released i'll update the git.

**Comment by RedDot-3ND7355** [comment]
Updated Git @DemonRem
