### ISSUE TITLE
[Request] Save last used server

### ISSUE THREAD

**Issue by Shadowfury22** [RedDot-3ND7355/BnS-Buddy#14]
Here's some context: my BnS-Buddy client has been thinking for a while that I'm using the Korean server and that forces me to select the European one every time I open it up. However, I didn't really want to complain about it because I thought it would prove non-trivial to debug it and find the root of the problem.

But now I just realized about something neat that would both solve my problem and be useful for the rest of the users: what about a setting to remember what was the last selected server on the drop down menu so the next time BnS-Buddy opens it selects that one instead of the default?

**Comment by RedDot-3ND7355** [comment]
Added to update 5.8.9.4
