### ISSUE TITLE
BNS 5.9.0.3 Source

### ISSUE THREAD

**Issue by DemonRem** [RedDot-3ND7355/BnS-Buddy#15]
can you please update the svn to the latest release

**Comment by RedDot-3ND7355** [comment]
I will update it, after I release the new 5.9.0.4 
as the code has been tampered and currently in test-build for some new features i'm adding.

**Comment by DemonRem** [comment]
ok

**Comment by RedDot-3ND7355** [comment]
It will take some time, because my hdd died. I'm going to recover it.

**Comment by DemonRem** [comment]
ok

**Comment by DemonRem** [comment]
>           It will take some time, because my hdd died. I'm going to recover it.

that mean your whole project gone or you have a backup ?

**Comment by RedDot-3ND7355** [comment]
It's gone for the time I can't access my files from my dead drive.

**Comment by DemonRem** [comment]
I give you small tip time since if something happened to the pc you always can download it from git, as you saw now ,

i suggest you always update the git to gain access your updated source incase something like that happened again ;)

**Comment by RedDot-3ND7355** [comment]
> I give you small tip time since if something happened to the pc you always can download it from git, as you saw now ,
> 
> i suggest you always update the git to gain access your updated source incase something like that happened again ;)

That ain't the issue, the progress is catchable. No problem.
But the real issue is the unique key I'm using to sign buddy that is stored on my dead drive.
Without it, even if I update buddy, no one could run it. Nor update to it.

**Comment by DemonRem** [comment]
hmm that is a bad issue can I help in something then?

**Comment by RedDot-3ND7355** [comment]
> hmm that is a bad issue can I help in something then?

No worries, I will be sending a donor PCB and original PCB to a team.
They'll do the soldering for me.

**Comment by DemonRem** [comment]
@RedDot-3ND7355 
i wonder bnsbuddy is back to work, that mean this is the time to git will be updated?

**Comment by RedDot-3ND7355** [comment]
@DemonRem the temp fix is an hot patched version.
So until i get my HDD back from mail I'll finish the actual update and push it here as well.

**Comment by RedDot-3ND7355** [comment]
@DemonRem  Managed to workaround not having my hdd but lost all current work on bns buddy.
Changelog posted on bnsbuddy.com or ReadMe.txt from updating buddy.
Source will be updated shortly.

**Comment by RedDot-3ND7355** [comment]
Source has been updated. Thanks for waiting.
