### ISSUE TITLE
Null reference exception

### ISSUE THREAD

**Issue by Shadowfury22** [RedDot-3ND7355/BnS-Buddy#16]
![image](https://user-images.githubusercontent.com/2363492/48642679-d8d9d980-e9dd-11e8-9670-b4669c19ac8b.png)

I'm getting this error for some reason since a few days ago just after clicking "sign in".

**Comment by Shadowfury22** [comment]
I already tried deleting the settings file and the bnsbuddy executable file to no avail :(

**Comment by crazydisi** [comment]
Please visit the BnSBuddy Discord and read the #announement channel. There is an alterantive Launcher at the moment.

**Comment by DemonRem** [comment]
they found seloution for the problem,
i hope they will update the git now

**Comment by RedDot-3ND7355** [comment]
Issue fixed, update pushed.
