### ISSUE TITLE
No bitness was selected (Addon)

### ISSUE THREAD

**Issue by laayhood** [RedDot-3ND7355/BnS-Buddy#17]
The problem occur when i pressed play button after selected addon i want to use.
![capture](https://user-images.githubusercontent.com/45703204/49680266-a64b6a00-facd-11e8-92fc-9c770569c8c7.PNG)
try to use google and bnsbuddy forum to find solution but nothing came up.

thanks!

**Comment by RedDot-3ND7355** [comment]
Edit the existing addon with the addon creator.
where it says config.dat or config64.dat
Must be changed to config[bit].dat
save the addon and refresh. then try again ;)

**Comment by laayhood** [comment]
![annotation 2018-12-09 070740](https://user-images.githubusercontent.com/45703204/49691596-35fe2080-fb81-11e8-9177-44a47e9ae016.jpg)
i did =/
edit: it must do like this xml[64].dat or the picture is right one?

**Comment by RedDot-3ND7355** [comment]
@laayhood i mean, literally changing xml64.dat TO xml[bit].dat
it has to say [bit] not 64, not [64]. Only [bit]

**Comment by laayhood** [comment]
Thanks xEndless the issue is solved. thanks again!
