### ISSUE TITLE
Flies account verification

### ISSUE THREAD

**Issue by Logonius** [RedDot-3ND7355/BnS-Buddy#19]
Hi, I'm from Russia, I use bns buddy and english patch, I bought an account BNS Korea and using bns buddy and Eglish patch and I have every week flies account verification (banit), tell me why this happens, and how to do so to safely play with bns buddy and english patch. Thank you in advance.

P. S I do not have a Korean phone number, so I find it difficult to verify the account.

**Comment by RedDot-3ND7355** [comment]
You have to update the game every week. It's completely normal.
Just reapply the "patch" every week.

BnS Buddy only verifies via code that you get on your email from mail server.

Other than that, there's nothing I can do.
