### ISSUE TITLE
[Request] 64bin dats decompiler

### ISSUE THREAD

**Issue by GooG2e** [RedDot-3ND7355/BnS-Buddy#2]
Hello!
Can you make standalone decompiler for 64bit dat files as console program.
Thank you!

**Comment by RedDot-3ND7355** [comment]
After BnS Buddy is updated, i'll consider ;)

**Comment by smoguk** [comment]
yes please update the source so I can change to save my login data :)

**Comment by harrybobo0328** [comment]
Also wish you to do this, too
or just let me choose the XML file anywhere so I don't need to decompile it on my SSD
Thanks a lot!

**Comment by RedDot-3ND7355** [comment]
Updated Source.

**Comment by RedDot-3ND7355** [comment]
https://github.com/RedDot-3ND7355/BuddyDatCom/blob/master/BuddyDatCom/bin/Debug/BuddyDatCom.exe
https://github.com/RedDot-3ND7355/BuddyDatCom/blob/master/BuddyDatCom/bin/Debug/DatEditingDll.dll
