### ISSUE TITLE
Japanese Blade & Soul Error

### ISSUE THREAD

**Issue by DemonRem** [RedDot-3ND7355/BnS-Buddy#20]
@RedDot-3ND7355 there is an error when I try to choose the Japanese version of blade and soul .

Ionic.Zlib.ZlibException : Bad State (Unknown compression method (0x26))

what shell I do?

**Comment by RedDot-3ND7355** [comment]
@DemonRem got an in depth error log?

**Comment by RedDot-3ND7355** [comment]
@DemonRem Problem is solved?

**Comment by DemonRem** [comment]
yes

**Comment by pureche** [comment]
@DemonRem how did you fix the problem?
