### ISSUE TITLE
xml unpack encryption/decryption key update

### ISSUE THREAD

**Issue by ThePureCC** [RedDot-3ND7355/BnS-Buddy#22]
The whole unpacking process no longer works as of Jan. 22 2020. 

I was wondering if anyone knows how to find that unpack/pack encryption key.

I saw on the bns buddy official site, as of version 5.9.3.4 the updated key was added to it, but github isn't being updated in real time. @RedDot-3ND7355 would you please consider updating the key in the source code? Or maybe show us how to find the key.

Much appreciated.

**Comment by RedDot-3ND7355** [comment]
Sadly, I won't show how to get it. Even if it's REALLY easy.
The only thing you need is an RE tool or debugging tool in general.
or HEX tool. Hook to the game or open exe via hex tool and should be there in plain text.

**Comment by ThePureCC** [comment]
@RedDot-3ND7355 Thanks, that's all I needed to know. 

I've noticed that they tried to mix the key up to prevent brute force cracks. You can delete this issue if you want, so that they don't encrypt the encryption key.

**Comment by Arbalest1337** [comment]
@RedDot-3ND7355 @pureche  How can i get the new key?  I tried to use UltraEdit to open Client64.exe, but I don't know what to look for .

**Comment by ThePureCC** [comment]
@Arbalest-Dcmk I don't know how either. I tried opening up in hex, didn't find anything related. I have a rough idea of how, but I haven't been home to test it out.

**Comment by pureche** [comment]
@RedDot-3ND7355 Sorry to bother you again. I tried to use OllyDebug and Hex tools to open up Client.exe, but there's nothing useful in there. And OD won't attach to the game process because it can't find it. Could you please shed some light on this?

**Comment by RedDot-3ND7355** [comment]
@Arbalest-Dcmk @pureche 
1: Get xdbg32/64 with ScyllaHide addon
2: Hook up the client.exe with xdbg (bin/client.exe for xdbg32 | bin64/client.exe for xdbg64)
3: Start the client with argument /LaunchByLauncher
4: Hit next until the popup appears, pause/freeze process
5: Search within the Client.exe module in memory map WITHIN the empty txt area
6: After it scanned the whole memory area for strings, Use the regex filter and search for 16 characters long string.
7: Find the good string within the list of 1000 strings x'D
8: Profit.

**Comment by ThePureCC** [comment]
@RedDot-3ND7355 Thanks. Much appreciated.

**Comment by ThePureCC** [comment]
@RedDot-3ND7355 Could you please give some insights on the latest update that happened today? June 24 2020. I found the string, it was used before, but didn't exactly unpack the dat file.

**Comment by RedDot-3ND7355** [comment]
@pureche they added a 1024bit signature validation. and it is to be applied on every region in a near future.
we are already working on it to support it. But sadly we can't recreate a valid signature due to it using rsa private keys.

So we are also working on making a bypass for the check.

**Comment by ThePureCC** [comment]
@RedDot-3ND7355 What does that mean? it means repacking the dat file will no longer work?

**Comment by RedDot-3ND7355** [comment]
@pureche temporary.

**Comment by ThePureCC** [comment]
> @pureche temporary.

Alright, Please keep me updated.
