### ISSUE TITLE
stuck at loading

### ISSUE THREAD

**Issue by DemonRem** [RedDot-3ND7355/BnS-Buddy#23]
@RedDot-3ND7355 
listen i compiled the source but its stuck in loading for about like 1 hour i even take a sleep and yet its loading :(
![1](https://user-images.githubusercontent.com/29927382/87880257-f81ddb00-c9f8-11ea-8769-332bacfce9a2.png)

**Comment by RedDot-3ND7355** [comment]
Check the event viewer and see if the errors are showing up there.
