### ISSUE TITLE
Addons issue

### ISSUE THREAD

**Issue by DarkhShadow** [RedDot-3ND7355/BnS-Buddy#5]
I have created 2 addons, one edits config64.xml and the other one edits xml64.dat.

The config64 one works as expected, but the xml64 one does NOT, it simply comes up with this error http://i.imgur.com/Trh5QVP.png, full log here https://pastebin.com/1Qe0CFNR.

The contents of my xml64 addon are as follows.
https://pastebin.com/j4gkWHQn

Have I made a mistake or is this a legitimate bug?

**Comment by RedDot-3ND7355** [comment]
Thanks for reporting the errors!
I'm already working on a fix :+1:

**Comment by RedDot-3ND7355** [comment]
Problem fixed in next version!
