### ISSUE TITLE
"Remember me" not working as expected

### ISSUE THREAD

**Issue by healiha** [RedDot-3ND7355/BnS-Buddy#6]
Since last update, when the multiple account was introduced I've been unable to use this feature.

I've taken a look at the regs and the account (folder name) and reg keys are present inside, but when on the login form, the list of saved accounts is always empty.

Using Windows 8.1

**Comment by makethegod** [comment]
Same here, please fix it quick 👍 

Win 10 here

**Comment by RedDot-3ND7355** [comment]
Problem found and issue fixed in next version. ;)
