### ISSUE TITLE
Feature request: Bitness-agnostic addons

### ISSUE THREAD

**Issue by alexrp** [RedDot-3ND7355/BnS-Buddy#7]
Hello,

I've been writing a few addons to make my life easier whenever a new patch is deployed. One thing that results in a lot of repetition, though, is the fact that I have to write two separate files for the 32-bit and 64-bit client. For example, to disable Nagle in arena for both 32-bit and 64-bit, I need these files:

```
FileName = config64.dat.files\\system.config2.xml
Search = <option name="use-nagle-arena" value="true" />
Replace = <option name="use-nagle-arena" value="false" />
Description = Disable Nagle's algorithm in arena (64-bit)
```

```
FileName = config.dat.files\\system.config2.xml
Search = <option name="use-nagle-arena" value="true" />
Replace = <option name="use-nagle-arena" value="false" />
Description = Disable Nagle's algorithm in arena (32-bit)
```

I'm wondering if a special variable, e.g. `${bits}`, could be introduced, so I could just write a single file like this:

```
FileName = config${bits}.dat.files\\system.config2.xml
Search = <option name="use-nagle-arena" value="true" />
Replace = <option name="use-nagle-arena" value="false" />
Description = Disable Nagle's algorithm in arena
```

When BnS Buddy sees that an addon uses `${bits}` in its `FileName` component, it would know that this addon should be applied to both 32-bit and 64-bit clients. When applying it to the 64-bit client, `${bits}` would be replaced with `64`, and for the 32-bit client, it would just be replaced with the empty string, so the above would expand to `config64.dat.files\\system.config2.xml` and `config.dat.files\\system.config2.xml`.

Would this be feasible to implement?

**Comment by RedDot-3ND7355** [comment]
Sadly I won't implement this. The reason why is that you don't need don't need to do both to play the game. only 1. wich is depending on the client you decide to play with. 

But I sure do understand, it's to save user time and not having to create two patches or ticking 2 boxes.
